# -*- coding: utf-8 -*-
"""Student Performance

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D9RZg0ai4yjIyPTTAfhJB4QPfuj-u63x
"""

import pandas as pd

from pathlib import Path

file_path = Path(__file__).parent / "StudentPerformanceFactors.csv"
df = pd.read_csv(file_path)

df.head()



df.shape

df.info()

df.isnull().sum()

df["Teacher_Quality"].value_counts(dropna=False)

df["Parental_Education_Level"].value_counts(dropna=False)

df["Distance_from_Home"].value_counts(dropna=False)

df["Teacher_Quality"] = df["Teacher_Quality"].fillna(
    df["Teacher_Quality"].mode()[0]
)

df["Parental_Education_Level"] = df["Parental_Education_Level"].fillna(
    df["Parental_Education_Level"].mode()[0]
)

df["Distance_from_Home"] = df["Distance_from_Home"].fillna(
    df["Distance_from_Home"].mode()[0]
)

df.isnull().sum()

df.duplicated().sum()

df.describe()

df["Exam_Score"].sort_values(ascending=False).head(20)

df["Exam_Score"].value_counts().sort_index()

df[df["Exam_Score"] == 101]

import matplotlib.pyplot as plt

plt.hist(df["Exam_Score"], bins=20)
plt.xlabel("Exam Score")
plt.ylabel("Number of Students")
plt.title("Distribution of Exam Scores")
plt.show()

plt.scatter(df["Hours_Studied"], df["Exam_Score"])
plt.xlabel("Hours Studied")
plt.ylabel("Exam Score")
plt.title("Hours Studied vs Exam Score")
plt.show()

df["Hours_Studied"].corr(df["Exam_Score"])

df["Attendance"].corr(df["Exam_Score"])

df.select_dtypes(include="number").corr()["Exam_Score"].sort_values(ascending=False)

X = df.drop("Exam_Score", axis=1)
y = df["Exam_Score"]

X.shape, y.shape

X.select_dtypes(include="object").columns

X_encoded = pd.get_dummies(X, drop_first=True)

X_encoded.shape

X_encoded.head()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded,
    y,
    test_size=0.2,
    random_state=42
)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled.shape, X_test_scaled.shape

from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor(n_neighbors=5)

knn.fit(X_train_scaled, y_train)

y_pred = knn.predict(X_test_scaled)

y_pred[:10]

comparison = pd.DataFrame({
    "Actual": y_test.values[:10],
    "Predicted": y_pred[:10]
})

comparison

from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)

print("MAE:", mae)

from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)

print("R²:", r2)

from sklearn.tree import DecisionTreeRegressor

tree = DecisionTreeRegressor(random_state=42)

tree.fit(X_train, y_train)

tree_pred = tree.predict(X_test)

from sklearn.metrics import mean_absolute_error, r2_score

tree_mae = mean_absolute_error(y_test, tree_pred)
tree_r2 = r2_score(y_test, tree_pred)

print("Decision Tree MAE:", tree_mae)
print("Decision Tree R²:", tree_r2)

tree2 = DecisionTreeRegressor(
    max_depth=5,
    random_state=42
)

tree2.fit(X_train, y_train)

tree2_pred = tree2.predict(X_test)

tree2_mae = mean_absolute_error(y_test, tree2_pred)
tree2_r2 = r2_score(y_test, tree2_pred)

print("Decision Tree MAE:", tree2_mae)
print("Decision Tree R²:", tree2_r2)

importance = pd.Series(
    tree2.feature_importances_,
    index=X_train.columns
).sort_values(ascending=False)

importance.head(10)

cluster_features = [
    "Hours_Studied",
    "Attendance",
    "Sleep_Hours",
    "Previous_Scores",
    "Tutoring_Sessions",
    "Physical_Activity"
]

X_cluster = df[cluster_features]

X_cluster.head()

from sklearn.preprocessing import StandardScaler

cluster_scaler = StandardScaler()

X_cluster_scaled = cluster_scaler.fit_transform(X_cluster)

X_cluster_scaled[:5]

from sklearn.cluster import KMeans

kmeans = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

clusters = kmeans.fit_predict(X_cluster_scaled)

clusters[:20]

pd.Series(clusters).value_counts().sort_index()

df_clustered = X_cluster.copy()
df_clustered["Cluster"] = clusters

df_clustered.groupby("Cluster").mean()

cluster_centers = pd.DataFrame(
    cluster_scaler.inverse_transform(kmeans.cluster_centers_),
    columns=cluster_features
)

cluster_centers

df_with_clusters = df.copy()
df_with_clusters["Cluster"] = clusters

df_with_clusters.groupby("Cluster")["Exam_Score"].mean()

inertias = []

for k in range(2, 9):
    km = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )
    km.fit(X_cluster_scaled)
    inertias.append(km.inertia_)

plt.plot(range(2, 9), inertias, marker="o")
plt.xlabel("Number of Clusters (k)")
plt.ylabel("Inertia")
plt.title("Elbow Method")
plt.show()

kmeans4 = KMeans(
    n_clusters=4,
    random_state=42,
    n_init=10
)

clusters4 = kmeans4.fit_predict(X_cluster_scaled)

df_clustered4 = X_cluster.copy()
df_clustered4["Cluster"] = clusters4

df_clustered4.groupby("Cluster").mean()

print("Top numerical correlations:")
print(df.select_dtypes(include="number").corr()["Exam_Score"].sort_values(ascending=False))

print("\nTop Decision Tree features:")
print(importance.head(10))

plt.scatter(df["Attendance"], df["Exam_Score"])
plt.xlabel("Attendance")
plt.ylabel("Exam Score")
plt.title("Attendance vs Exam Score")
plt.show()

plt.scatter(df["Hours_Studied"], df["Exam_Score"])
plt.xlabel("Hours Studied")
plt.ylabel("Exam Score")
plt.title("Hours Studied vs Exam Score")
plt.show()

plt.scatter(df["Attendance"], df["Exam_Score"])
plt.xlabel("Attendance")
plt.ylabel("Exam Score")
plt.title("Attendance vs Exam Score")
plt.show()

df["Attendance_Group"] = pd.cut(
    df["Attendance"],
    bins=[0, 60, 70, 80, 90, 100],
    labels=["≤60", "61–70", "71–80", "81–90", "91–100"]
)

attendance_scores = df.groupby(
    "Attendance_Group",
    observed=True
)["Exam_Score"].mean()

print(attendance_scores)

print(df["Hours_Studied"].min())
print(df["Hours_Studied"].max())

df["Study_Hours_Group"] = pd.cut(
    df["Hours_Studied"],
    bins=[0, 10, 20, 30, 40, 44],
    labels=["1–10", "11–20", "21–30", "31–40", "41–44"]
)

study_scores = df.groupby(
    "Study_Hours_Group",
    observed=True
)["Exam_Score"].mean()

print(study_scores)

import matplotlib.pyplot as plt

attendance_scores.plot(kind="bar")

plt.xlabel("Attendance Group")
plt.ylabel("Average Exam Score")
plt.title("Average Exam Score by Attendance Group")
plt.xticks(rotation=0)
plt.show()

study_scores.plot(kind="bar")

plt.xlabel("Study Hours Group")
plt.ylabel("Average Exam Score")
plt.title("Average Exam Score by Study Hours Group")
plt.xticks(rotation=0)
plt.show()

comparison = pd.DataFrame({
    "Factor": ["Attendance", "Hours Studied"],
    "Lowest_Group_Avg": [attendance_scores.iloc[0], study_scores.iloc[0]],
    "Highest_Group_Avg": [attendance_scores.iloc[-1], study_scores.iloc[-1]]
})

comparison["Difference"] = (
    comparison["Highest_Group_Avg"] -
    comparison["Lowest_Group_Avg"]
)

print(comparison)

# Plot comparison of low-to-high group differences

comparison.plot(
    x="Factor",
    y="Difference",
    kind="bar"
)

plt.xlabel("Factor")
plt.ylabel("Difference in Average Exam Score")
plt.title("Change in Average Exam Score")
plt.xticks(rotation=0)
plt.show()