# -*- coding: utf-8 -*-
"""Penguins Dataset

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D0KNb97qSKWQmFJc-cwaawhLuJHGYnEf
"""

import pandas as pd

df = pd.read_csv("penguins_size.csv")

df.head()

df.info()

df.describe()

df["species"].value_counts()

df["island"].value_counts()

df["sex"].value_counts()

df[df["sex"].isna()]

df[df["sex"] == "."]

df["sex"] = df["sex"].replace(".", pd.NA)

df = df.dropna(
    subset=[
        "culmen_length_mm",
        "culmen_depth_mm",
        "flipper_length_mm",
        "body_mass_g"
    ],
    how="all"
)

df.shape

df.isna().sum()

df["species"].value_counts()

df["species"].value_counts(normalize=True) * 100

df["species"].value_counts()

normalize=True

pd.crosstab(df["island"], df["species"])

df.groupby("species")["body_mass_g"].mean()

df.groupby("species")["body_mass_g"].max()

df.groupby("species")["flipper_length_mm"].mean()

df.groupby("species")["culmen_length_mm"].mean()

df.groupby("species")["culmen_depth_mm"].mean()

df.plot.scatter(
    x="flipper_length_mm",
    y="body_mass_g"
)

df["flipper_length_mm"].corr(df["body_mass_g"])

import matplotlib.pyplot as plt

plt.plot([1, 2, 3, 4, 5])
plt.show()

import matplotlib.pyplot as plt

plt.scatter(df["flipper_length_mm"], df["body_mass_g"])

plt.xlabel("Flipper length (mm)")
plt.ylabel("Body mass (g)")
plt.title("Flipper Length vs Body Mass")

plt.show()

plt.scatter(
    df[df["species"] == "Adelie"]["flipper_length_mm"],
    df[df["species"] == "Adelie"]["body_mass_g"],
    label="Adelie"
)

plt.scatter(
    df[df["species"] == "Chinstrap"]["flipper_length_mm"],
    df[df["species"] == "Chinstrap"]["body_mass_g"],
    label="Chinstrap"
)

plt.scatter(
    df[df["species"] == "Gentoo"]["flipper_length_mm"],
    df[df["species"] == "Gentoo"]["body_mass_g"],
    label="Gentoo"
)

plt.xlabel("Flipper length (mm)")
plt.ylabel("Body mass (g)")
plt.title("Flipper Length vs Body Mass by Species")
plt.legend()

plt.show()

df["body_mass_g"].max()

df["body_mass_g"].min()

df["flipper_length_mm"].max()

df["flipper_length_mm"].min()

df.loc[df["body_mass_g"].idxmax()]

df["island"].value_counts()

df.groupby("island")["body_mass_g"].mean()

plt.hist(df["body_mass_g"])
plt.xlabel("body mass (g)")
plt.ylabel("Number of penguins")
plt.title("Distribution of Penguin Body Mass")
plt.show()

plt.hist(df["flipper_length_mm"])
plt.xlabel("flipper_length (mm)")
plt.ylabel("Number of penguins")
plt.title("Distribution of Penguin flipper_length")
plt.show()