# -*- coding: utf-8 -*-
"""Copie de ML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GshXTyYzao_M05PQm_jjbx8if-QlVidX
"""

# Module 4 — Introduction au Machine Learning
## Correction complète des exercices — Google Colab
# Importer les librairies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_digits
from sklearn.metrics import confusion_matrix
from sklearn.datasets import load_iris

iris = load_iris()
X = iris.data
y = iris.target

print("Forme de X :", X.shape)
print("Forme de y :", y.shape)
print("Classes :", iris.target_names)

"""##
 Séparer Train et Test


"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("X_train :", X_train.shape)
print("X_test  :", X_test.shape)
print("y_train :", y_train.shape)
print("y_test  :", y_test.shape)

"""#
 Challenge KNN


"""

# 1. Importer KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier

# 2. Créer et entraîner le modèle (K = 5)
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train)

# 3. Calculer l'accuracy sur X_test
print("Accuracy (K=5) :", model.score(X_test, y_test))

# 4. Tester avec K = 1
model_k1 = KNeighborsClassifier(n_neighbors=1)
model_k1.fit(X_train, y_train)
print("Accuracy (K=1) :", model_k1.score(X_test, y_test))

# Tester avec K = 15
model_k15 = KNeighborsClassifier(n_neighbors=15)
model_k15.fit(X_train, y_train)
print("Accuracy (K=15) :", model_k15.score(X_test, y_test))

# Tester K de 1 à 20
neighbors = np.arange(1, 21)
train_accuracy = np.empty(len(neighbors))
test_accuracy = np.empty(len(neighbors))

for i, k in enumerate(neighbors):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    train_accuracy[i] = knn.score(X_train, y_train)
    test_accuracy[i] = knn.score(X_test, y_test)

import matplotlib.pyplot as plt

# Visualisation taux d'apprentissage et test
plt.figure(figsize=(12, 6))
plt.title('k-NN précision par nombre de voisins')
plt.scatter(neighbors, test_accuracy,
            label='Test Accuracy', color="green")
plt.scatter(neighbors, train_accuracy,
            label='Train Accuracy', color="red")
plt.legend()
plt.xlabel('Nombre de voisins')
plt.ylabel('Précision')
plt.show()

"""#
Challenge Decision Tree


"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

# 1. Créer l'arbre avec une profondeur maximale de 3
model = DecisionTreeClassifier(max_depth=3)

# 2. Entraîner l'arbre
model.fit(X_train, y_train)

# 3. Calculer l'accuracy
accuracy = model.score(X_test, y_test)

print("Accuracy :", accuracy)

# 4. Visualiser l'arbre
plt.figure(figsize=(15, 8))
plot_tree(model, filled=True)
plt.show()

model_none = DecisionTreeClassifier(max_depth=None)
model_none.fit(X_train, y_train)

accuracy_none = model_none.score(X_test, y_test)

print("Accuracy max_depth=3 :", accuracy)
print("Accuracy max_depth=None :", accuracy_none)

"""# SVM

"""

# 1. Importer SVC
from sklearn.svm import SVC

# 2. Créer et entraîner un SVM linéaire
model = SVC(kernel='linear')
model.fit(X_train, y_train)

# 3. Calculer l'accuracy sur X_test (SVM linéaire)
accuracy_linear = model.score(X_test, y_test)
print("Accuracy (kernel='linear') :", accuracy_linear)

# 4. Essayer un kernel rbf
model_rbf = SVC(kernel='rbf')
model_rbf.fit(X_train, y_train)

# 5. Calculer l'accuracy sur X_test (SVM RBF) et comparer
accuracy_rbf = model_rbf.score(X_test, y_test)
print("Accuracy (kernel='rbf')    :", accuracy_rbf)

"""#Non supervisé (algorithme de clustering)

"""

from sklearn.cluster import KMeans

model = KMeans(n_clusters=3, random_state=42, n_init=10)

model.fit(X)
# voir les groupes
clusters = model.labels_

print(clusters)
#visualiser les groupes
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))

plt.scatter(X[:, 0], X[:, 1], c=clusters)

plt.xlabel("Longueur du sépale")
plt.ylabel("Largeur du sépale")
plt.title("K-Means sur le dataset Iris")

plt.show()
#visualiser le centre de chaque groupe
print("Centres des clusters :")
print(model.cluster_centers_)
#graphique
plt.figure(figsize=(8, 6))

plt.scatter(X[:, 0], X[:, 1], c=clusters) #neyage

plt.scatter(
    model.cluster_centers_[:, 0],
    model.cluster_centers_[:, 1],
    marker="X",
    s=200
)

plt.xlabel("Longueur du sépale")
plt.ylabel("Largeur du sépale")
plt.title("K-Means : groupes et centres")

plt.show()
#comparer avec les vrais especes
from sklearn.metrics import adjusted_rand_score

score = adjusted_rand_score(y, clusters)

print("Score ARI :", score)