# -*- coding: utf-8 -*-
"""TP3_Correction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12UKcVfv35yQc5MigOTykGrKFmsIkkzHv

# TP3 —

## SETUP — Charger le dataset
"""

import pandas as pd              # pandas : manipuler des tableaux de données
import numpy as np                # numpy : calcul numérique
import matplotlib.pyplot as plt   # matplotlib : graphiques

url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2021/2021-04-20/netflix_titles.csv"
df = pd.read_csv(url)             # charge le CSV directement depuis internet

print("Nombre de lignes :", len(df))  # affiche le nombre de lignes
df.head()                             # affiche les 5 premières lignes

"""## PARTIE A — Nettoyage

**Q1 — Doublons stricts et partiels**
"""

print(df.duplicated().sum())
# duplicated() = True si la ligne est un doublon exact ; sum() = les compte

print(df.duplicated(subset=['title', 'country', 'release_year']).sum())
# même chose mais en comparant seulement ces 3 colonnes

"""**Q2 — Caractère invisible dans les titres**"""

mask = df['title'].str.contains('\u200b', na=False)
# contains() cherche le caractère invisible dans chaque titre ; renvoie True/False

print(mask.sum())              # compte combien de titres sont concernés
print(repr(df.loc[mask, 'title'].iloc[0]))
# repr() affiche le texte brut, pour rendre visible le caractère invisible

df['title'] = df['title'].str.replace('\u200b', '', regex=False)
# replace() enlève ce caractère de toute la colonne (fonction du mémo)

"""**Q3 — Convertir date_added en date**"""

print(df['date_added'].dtype)          # affiche le type AVANT (texte)

df['date_added'] = pd.to_datetime(df['date_added'].str.strip(), errors='coerce')
# str.strip() enlève les espaces en trop
# pd.to_datetime() convertit le texte en vraie date
# errors='coerce' : si une valeur ne peut pas être convertie, elle devient NaT (vide) au lieu de planter

print(df['date_added'].dtype)          # affiche le type APRES (date)

"""**Q4 — Séparer duration en deux colonnes**"""

is_movie = df['type'] == 'Movie'
# is_movie = True pour les films, False pour les séries

df['duration_minutes'] = np.nan        # crée la colonne, vide pour l'instant
df['duration_seasons'] = np.nan        # crée la colonne, vide pour l'instant

df.loc[is_movie, 'duration_minutes'] = df.loc[is_movie, 'duration'].str.extract(r'(\d+)')[0].astype(float)
# str.extract(r'(\d+)') extrait juste le nombre du texte (ex: '93 min' -> '93')
# [0] récupère ce nombre comme une colonne normale
# astype(float) transforme le texte en nombre décimal

df.loc[~is_movie, 'duration_seasons'] = df.loc[~is_movie, 'duration'].str.extract(r'(\d+)')[0].astype(float)
# ~is_movie = l'inverse de is_movie, donc les séries

"""**Q5 — Vérifier les types de colonnes**"""

print(df.dtypes)
# dtypes affiche le type de chaque colonne (texte, nombre, date...)

"""## PARTIE B — Valeurs manquantes

**Q1 — Compter les valeurs manquantes**
"""

print(df.isna().sum())
# isna() = True pour chaque case vide ; sum() = compte le total par colonne

"""**Q2, Q3, Q4 — Remplacer par une constante**"""

df['director'] = df['director'].fillna('Inconnu')
# fillna() remplace les valeurs vides par le texte donné

df['cast'] = df['cast'].fillna('Non renseigné')
# même chose pour cast

df['country'] = df['country'].fillna('Inconnu')
# même chose pour country

"""**Q5 — Supprimer les lignes concernées**"""

avant = len(df)                              # nombre de lignes avant

df = df.dropna(subset=['date_added', 'rating'])
# dropna(subset=[...]) supprime les lignes vides SEULEMENT sur ces colonnes

print("Lignes supprimées :", avant - len(df))

"""**Q6 — Vérifier qu'il ne reste plus de manquants**"""

print(df.isna().sum())
# on relance le même comptage qu'à la Q1 pour vérifier

"""## PARTIE C — Données aberrantes

**Q1 — Boxplot de release_year**
"""

plt.boxplot(df['release_year'])   # boxplot() affiche la boîte à moustaches
plt.title("Boxplot - release_year")
plt.show()                        # affiche le graphique

"""**Q2 — Calculer Q1, Q3 et IQR**"""

Q1 = df['release_year'].quantile(0.25)   # quantile(0.25) = 1er quartile
Q3 = df['release_year'].quantile(0.75)   # quantile(0.75) = 3e quartile
IQR = Q3 - Q1                            # IQR = écart interquartile

print("Q1 =", Q1, "| Q3 =", Q3, "| IQR =", IQR)

"""**Q3 — Bornes et nombre d'aberrants**"""

borne_basse = Q1 - 1.5 * IQR      # règle des 1,5 x IQR
borne_haute = Q3 + 1.5 * IQR

aberrants = df[(df['release_year'] < borne_basse) | (df['release_year'] > borne_haute)]
# on garde les lignes EN DEHORS de l'intervalle [borne_basse, borne_haute]

print("Bornes :", borne_basse, "-", borne_haute)
print("Nombre d'aberrants :", len(aberrants))

"""**Q4 — Erreurs de saisie ou vraies données ? (pas de code, réponse à l'oral)**

Réponse courte : NON, ce ne sont pas des erreurs. Netflix propose vraiment de vieux films (jusqu'en 1925). On les GARDE — la règle IQR sert juste à repérer des cas à vérifier, pas à supprimer automatiquement.

## PARTIE D — Encodage

**Q1 — Nombre de catégories distinctes**
"""

print(df['type'].nunique())     # nunique() = nombre de valeurs différentes
print(df['rating'].nunique())
print(df['rating'].unique())    # unique() = liste ces valeurs

"""**Q2 — Label Encoding de rating**"""

list(df['rating'].unique())
print(list(df['rating'].unique()))
ordre = ['G', 'TV-Y', 'TV-G', 'PG', 'TV-Y7', 'TV-Y7-FV', 'PG-13',
         'TV-PG', 'TV-14', 'R', 'TV-MA', 'NC-17', 'NR', 'UR']
# liste du plus permissif au plus restrictif

dict_ordre = {r: i for i, r in enumerate(ordre)}
# crée un dictionnaire {'G': 0, 'TV-Y': 1, ...}

df['rating_enc'] = df['rating'].map(dict_ordre)
# map() remplace chaque texte par son numéro dans le dictionnaire

print(df['rating_enc'].head())

"""**Q3 et Q4 — One-Hot Encoding de type**"""

avant = df.shape[1]              # shape[1] = nombre de colonnes AVANT

df = pd.get_dummies(df, columns=['type'], prefix='type')
# get_dummies() transforme 'type' en plusieurs colonnes 0/1 (une par catégorie)

apres = df.shape[1]              # nombre de colonnes APRES

print("Colonnes avant :", avant, "| Colonnes après :", apres)

"""## PARTIE E — Normalisation

**Q1 — MinMaxScaler sur release_year**
"""

from sklearn.preprocessing import MinMaxScaler
# MinMaxScaler ramène les valeurs entre 0 et 1

scaler = MinMaxScaler()
df['release_year_norm'] = scaler.fit_transform(df[['release_year']])
# fit_transform() calcule le min/max PUIS applique la transformation

print(df['release_year_norm'].describe())

"""**Q2 et Q3 — StandardScaler + vérification**"""

from sklearn.preprocessing import StandardScaler
# StandardScaler centre-réduit : moyenne 0, écart-type 1

films = df[df['type_Movie'] == True].copy()
# on garde uniquement les films (colonne créée par le One-Hot Encoding)

scaler2 = StandardScaler()
films['duration_std'] = scaler2.fit_transform(films[['duration_minutes']])

print(films['duration_std'].describe())
# describe() vérifie : moyenne proche de 0, écart-type proche de 1

"""## PARTIE F — Analyse exploratoire (EDA)

**Q1 — describe() sur les colonnes numériques**
"""

print(df.describe())
# describe() donne count, moyenne, écart-type, min, quartiles, max

print(df.describe().loc['std'].sort_values(ascending=False))
# on trie juste la ligne "std" (écart-type) pour trouver le plus grand

"""**Q2 — value_counts() : répartition et pays**"""

print(df['type_Movie'].value_counts())
# value_counts() compte le nombre de True/False (films vs séries)

df['country_main'] = df['country'].str.split(',').str[0]
# split(',') coupe le texte à chaque virgule -> liste de pays
# str[0] garde seulement le premier pays de la liste

print(df['country_main'].value_counts().head(5))
# top 5 des pays les plus fréquents

"""**Q3 — Corrélation release_year / duration_minutes**"""

print(df[['release_year', 'duration_minutes']].corr())
# corr() calcule la corrélation entre les deux colonnes (entre -1 et 1)

"""**Q4 — groupby('type') sur release_year**"""

print(df.groupby('type_Movie')['release_year'].mean())
# groupby() regroupe par valeur (True/False) puis mean() calcule la moyenne
# de release_year pour chaque groupe

"""## PARTIE G — Visualisation

**Q1 — Histogramme (Matplotlib)**
"""

plt.hist(df['release_year'], bins=30)   # hist() = histogramme, 30 barres
plt.title("Distribution des années de sortie")
plt.xlabel("release_year")
plt.ylabel("Nombre de titres")
plt.show()

"""**Q2 — Barres des 10 ratings les plus fréquents (Matplotlib)**"""

top10 = df['rating'].value_counts().head(10)
# value_counts() compte, head(10) garde les 10 premiers

plt.bar(top10.index, top10.values)   # bar() = diagramme en barres
plt.title("Top 10 des classifications")
plt.xticks(rotation=45)              # incline les étiquettes pour la lisibilité
plt.show()

"""**Q3 — Nuage de points année/durée, films uniquement (Matplotlib)**"""

films = df[df['type_Movie'] == True]

plt.scatter(films['release_year'], films['duration_minutes'])
# scatter() = un point par film (x=année, y=durée)
plt.xlabel("release_year")
plt.ylabel("duration_minutes")
plt.show()

"""**Q4 — Nuage de points interactif coloré par rating (Plotly)**"""

import plotly.express as px

fig = px.scatter(
    films,
    x="release_year",
    y="duration_minutes",
    color="rating"
)

fig.show()

"""**Q5 — Histogramme interactif par type (Plotly)**"""

fig2 = px.histogram(df, x="release_year", color="type_Movie")
# px.histogram() = équivalent interactif de plt.hist()
# color="type_Movie" sépare les couleurs film / série

fig2.show()